DROP DATABASE if EXISTS rj_lab4db;
CREATE DATABASE rj_lab4db;

USE rj_lab4db; CREATE TABLE users (
	userId BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
	firstName TINYTEXT NOT NULL,
	lastName TINYTEXT NOT NULL,
	userName VARCHAR(20) UNIQUE NOT NULL, 
	userPassword VARCHAR(128) NOT NULL,
	userPasswordSalt VARCHAR(128) NOT NULL,
	email VARCHAR(254) UNIQUE NOT NULL, 
	gender ENUM('male', 'female'), 
	creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); CREATE TABLE articles (
	articleID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL, 
	editorID BIGINT UNSIGNED,
	articleTitle VARCHAR(255) NOT NULL,
	submissionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
	pageText BLOB
); CREATE TABLE revisions (
	revisionID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL, 
	editorID BIGINT UNSIGNED,
	articleTitle VARCHAR(255) NOT NULL,
	submissionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
	pageText BLOB
);